#!/usr/bin/env node

const program = require('commander');
const shrink = require('./index');

program
  .version('0.0.1')
  .option('-f, --file <path>', 'Path to image file')
  .parse(process.argv);

if (program.file) {
  console.log('input: ', program.file);
  shrink(file);
} else {
  console.log();
}
